### ISSUE TITLE
Maintainers style problem

### ISSUE THREAD

**Issue by alessioalex** [nodejitsu/browsenpm.org#31] opened 2014-06-19 08:21 UTC
Checkout http://browsenpm.org/package/express - tjholowaychuk's name is not on the right side of the logo, but at the bottom

**Comment by 3rd-Eden** [comment] 2014-06-19 08:22
Duplicate of #20

**Closed as completed by 3rd-Eden** 2014-06-19 08:22 UTC

**Comment by 3rd-Eden** [comment] 2014-08-21 13:32
Fixed in nodejitsu/package-pagelet@master which now uses 2 columns instead of 3 to give it more space.
