### ISSUE TITLE
Looks bad on mobile && unusable

### ISSUE THREAD

**Issue by alessioalex** [nodejitsu/browsenpm.org#32] opened 2014-06-19 08:23 UTC
Hey guys, I normally click a lot on twitter links from my iPhone. Unfortunately the module page looks cut on mobile and the homepage is kind of unusable: I cannot type stuff to search for a module.

Is there a plan for a mobile version or do you intend to implement responsive design maybe?

**Comment by 3rd-Eden** [comment] 2014-06-19 11:06
Duplicate of #22

**Closed as completed by 3rd-Eden** 2014-06-19 11:06 UTC
